#! /bin/sh
# When this script is called, it will update file $DB,
# named after a device file in /dev. The name will be taken as the last
# sequence of alphanumeric characters from the script name.

UUID=l9s4pu6iyhe1pgzbnhanpxk27
DB=/var/lib/misc/lifetime_writes-
SYS_PREFIX=/sys/block/
SYS_SUFFIX=/stat
BOOT_ID=/proc/sys/kernel/random/boot_id
LOG_ALSO=false

test "$1" = "--debug" && shift || exec > /dev/null 2>& 1
set -e
trap 'test $? = 0 || logger -p user.err -t "$0" failure' 0

test "$1" = "--log" && { shift; LOG_ALSO=true; }

test "`expr 9223372036854775806 + 1`" = 9223372036854775807
dev=`basename -- "$0"`
dev=`expr x"$dev" : x'.*[^[:alnum:]]\([[:alnum:]]\{1,\}\)$'`
DB=$DB$dev-$UUID.dat
mkdir -p -- "`dirname -- "$DB"`"
sys=$SYS_PREFIX$dev$SYS_SUFFIX
test -e "$sys"
test -f "$BOOT_ID"
boot_time=`stat -c %Y -- "$BOOT_ID"`
boot_id=`cat "$BOOT_ID" | cksum | cut -d" " -f 1`
written=`awk '{print $7}' < "$sys"`
written=`expr $written \* 512`

test ! -e "$DB" && >> "$DB"
(
	flock -n 9
	LOGGING_SINCE=$boot_time
	CURRENT_BOOT_ID=
	WRITTEN_SINCE_BOOT=0
	WRITTEN_BEFORE=0
	. "$DB"
	if test "$CURRENT_BOOT_ID" != "$boot_id"
	then
		WRITTEN_BEFORE=`
			expr $WRITTEN_BEFORE + $WRITTEN_SINCE_BOOT || :
		`
	fi
	{
		echo LOGGING_SINCE=$LOGGING_SINCE
		echo CURRENT_BOOT_ID=$boot_id
        	echo WRITTEN_SINCE_BOOT=$written
        	echo WRITTEN_BEFORE=$WRITTEN_BEFORE
        } > "$DB"
        if $LOG_ALSO
        then
        	m="`expr $WRITTEN_BEFORE + $WRITTEN_SINCE_BOOT || :` bytes"
        	m=$m" have been written to /dev/$dev"
        	m=$m" since `date -d "@$LOGGING_SINCE" +%Y-%m-%d`"
        	logger -p user.notice -t "$0" "$m"
        fi
) 9< "$DB"
